version: 2.1

jobs:
  check-skip-ci:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: |
          set +e

          git fetch origin refs/notes/commits:refs/notes/commits
          git notes show | fgrep "[skip-ci]"
          if [ $? -eq 0 ]; then
            exit 1
          fi

          set -e
  my-job:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "Hello, World!"
      - run: echo "__DEBUG__"
      - run: echo $CIRCLE_SHA1

workflows:
  my-workflow:
    jobs:
      - check-skip-ci
      - my-job:
          requires:
            - check-skip-ci
