version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "Hello, World!
      - run: "__DEBUG__"
      - run: echo $CIRCLE_SHA1

workflows:
  my-workflow:
    jobs:
      - my-job
